export const Routes = {
  Home: "Home",
  Cart: "Cart",
  Info: "Info",
  Favourites: "Favourites",
  Splash: "Splash",
  Login: "Login",
  AuthTabs: "AuthTabs",
  GuestCheckout: "GuestCheckout",
  Map: "Map",
  PaymentMethod: "PaymentMethod",
  SubCategoryDetails: "SubCategoryDetails",
  NewAddress: "NewAddress",
  Checkout: "Checkout",
  Outlets: "Outlets",
  HomeBase: "HomeBase",
  Profile: "Profile",
  SubCategory: "SubCategory",
  AuthBase: "Auth",
  Otp: "Otp",
  SignupOtp: "SignupOtp",
  Pickup: "Pickup",
  OrderType: "OrderType",
  LoyaltyHistory: "LoyaltyHistory",
  OrderHistory: "OrderHistory",
  Deals: "Deals",
};
